import type { Metadata } from "next";
import { ArrowLeft, CalendarDays, CheckCircle2, MapPin, MessageCircle, Share2, Sparkles, TicketCheck, Users } from "lucide-react";
import { getPublicProgram } from "@/db/public-programs";

export const dynamic = "force-dynamic";
const origin = "https://tdapku.my.id";
function dateLabel(value: string | null) { if (!value) return "Jadwal segera diumumkan"; return new Intl.DateTimeFormat("id-ID", { dateStyle: "long", timeZone: "Asia/Jakarta" }).format(new Date(`${value}T00:00:00+07:00`)); }
function titleOf(p: { publicTitle: string; programTitle: string }) { return p.publicTitle || p.programTitle; }
function rupiah(value: number | null) { return new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value || 0); }

export async function generateMetadata({ params }: { params: Promise<{ code: string }> }): Promise<Metadata> {
  try { const p = await getPublicProgram((await params).code); if (!p) return { title: "Program TDA Pekanbaru" }; const title = `${titleOf(p)} — TDA Pekanbaru`; const description = p.tagline || p.description || `Informasi Program ${titleOf(p)} dari TDA Pekanbaru.`; const image = p.flyerKey ? `${origin}/api/public-programs/${p.programCode}/flyer` : undefined; return { title, description, openGraph: { title, description, type: "website", locale: "id_ID", url: `${origin}/program/${p.programCode.toLowerCase()}`, images: image ? [{ url: image, alt: `Flyer ${titleOf(p)}` }] : [] }, twitter: { card: image ? "summary_large_image" : "summary", title, description, images: image ? [image] : [] } }; } catch { return { title: "Program TDA Pekanbaru" }; }
}

export default async function PublicProgramPage({ params }: { params: Promise<{ code: string }> }) {
  const program = await getPublicProgram((await params).code).catch(() => null);
  if (!program) return <main className="grid min-h-screen place-items-center bg-[#f3f7f3] p-6 text-center"><div><h1 className="text-2xl font-bold">Program belum tersedia</h1><p className="mt-2 text-slate-600">Program belum dipublikasikan atau tautannya tidak valid.</p><a href="/program" className="mt-6 inline-flex rounded-xl bg-emerald-800 px-5 py-3 font-bold text-white">Lihat Program Lainnya</a></div></main>;
  const title = titleOf(program); const benefits = program.benefits.split("\n").map((x) => x.trim()).filter(Boolean); const registrationUrl = program.registrationEventId ? `/daftar/${program.registrationEventId}` : ""; const shareUrl = `${origin}/program/${program.programCode.toLowerCase()}`; const waText = encodeURIComponent(`*${title}*\n${program.tagline || "Program TDA Pekanbaru"}\n\nLihat informasi lengkap: ${shareUrl}`); const contact = program.contactPhone.replace(/^0/, "62").replace(/\D/g, "");
  return <main className="min-h-screen bg-[#f3f7f3] text-slate-950"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-5 py-4"><a href="/program" className="flex items-center gap-2 text-sm font-bold text-emerald-800"><ArrowLeft className="size-4"/>Semua Program</a><div className="flex items-center gap-3"><a href="/kalender" className="hidden text-sm font-bold text-emerald-800 sm:block">Kalender</a><img src="/tda-pekanbaru.png" alt="TDA Pekanbaru" className="h-11 w-24 rounded-lg bg-white object-contain"/></div></div></header>
    <section className="bg-[#0d2f20] text-white"><div className="mx-auto grid max-w-6xl gap-8 px-5 py-10 lg:grid-cols-[.72fr_1fr] lg:items-center lg:py-14"><div className="overflow-hidden rounded-3xl bg-gradient-to-br from-[#145c3c] to-[#17a66b] shadow-2xl">{program.flyerKey ? <img src={`/api/public-programs/${program.programCode}/flyer`} alt={`Flyer ${title}`} className="aspect-[4/5] size-full object-cover"/> : <div className="flex aspect-[4/5] flex-col justify-between p-8"><div className="flex items-center gap-2 font-bold text-emerald-200"><Sparkles className="size-5"/>TDA PEKANBARU 9.0</div><div><p className="text-sm font-bold text-emerald-200">{program.divisionName}</p><h2 className="mt-3 text-4xl font-black leading-tight">{title}</h2></div><p className="text-sm font-bold tracking-widest text-emerald-200">#{program.programCode}</p></div>}</div><div><p className="text-sm font-bold uppercase tracking-[.18em] text-emerald-300">Program {program.divisionName}</p><h1 className="mt-4 text-4xl font-black leading-tight sm:text-5xl">{title}</h1><p className="mt-5 text-lg leading-8 text-emerald-100">{program.tagline || "Belajar, bertumbuh, dan berkolaborasi bersama TDA Pekanbaru."}</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><Info icon={CalendarDays} label="Jadwal" value={dateLabel(program.eventDate || program.startDate)} /><Info icon={MapPin} label="Lokasi" value={program.eventLocation || "Segera diumumkan"} /><Info icon={Users} label="Penyelenggara" value={program.divisionName} /><Info icon={TicketCheck} label="Biaya" value={program.eventIsPaid ? "Program berbayar" : program.registrationEventId ? "Gratis" : "Lihat informasi program"} /></div><div className="mt-8 flex flex-col gap-3 sm:flex-row">{registrationUrl && program.registrationOpen ? <a href={registrationUrl} className="inline-flex min-h-12 items-center justify-center rounded-xl bg-emerald-400 px-6 font-bold text-emerald-950">Daftar Sekarang</a> : <span className="inline-flex min-h-12 items-center justify-center rounded-xl bg-white/10 px-6 font-bold text-emerald-100">{registrationUrl ? "Pendaftaran Ditutup" : "Pendaftaran Segera Dibuka"}</span>}<a href={`https://wa.me/?text=${waText}`} target="_blank" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/30 px-6 font-bold"><Share2 className="size-4"/>Bagikan</a></div></div></div></section>
    <div className="mx-auto grid max-w-6xl gap-6 px-5 py-10 lg:grid-cols-[1fr_.55fr]"><div className="space-y-6"><section className="rounded-3xl border bg-white p-6 shadow-sm sm:p-8"><h2 className="text-2xl font-bold">Tentang Program</h2><p className="mt-4 whitespace-pre-wrap text-base leading-8 text-slate-600">{program.description || program.tagline || "Informasi lengkap program akan segera diperbarui oleh penyelenggara."}</p></section>{benefits.length > 0 && <section className="rounded-3xl border bg-white p-6 shadow-sm sm:p-8"><h2 className="text-2xl font-bold">Manfaat yang Didapat</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{benefits.map((benefit) => <div key={benefit} className="flex gap-3 rounded-xl bg-emerald-50 p-4"><CheckCircle2 className="mt-0.5 size-5 shrink-0 text-emerald-700"/><p className="leading-6">{benefit}</p></div>)}</div></section>}</div><aside className="space-y-6">{Boolean(program.eventIsPaid) && <section className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="font-bold">Harga Pendaftaran</h2><div className="mt-4 grid gap-3"><PriceRow label="Member TDA" value={program.memberPrice}/><PriceRow label="Umum" value={program.publicPrice}/></div></section>}{program.audience && <section className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="font-bold">Program Ini Cocok Untuk</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-600">{program.audience}</p></section>}<section className="rounded-3xl bg-emerald-800 p-6 text-white"><h2 className="text-xl font-bold">{registrationUrl && program.registrationOpen ? "Pendaftaran Dibuka" : registrationUrl ? "Pendaftaran Ditutup" : "Informasi Pendaftaran"}</h2><p className="mt-3 text-sm leading-6 text-emerald-100">{registrationUrl && program.registrationOpen ? "Amankan tempat Anda melalui formulir resmi TDA Pekanbaru." : "Hubungi narahubung untuk informasi lebih lanjut mengenai program ini."}</p>{registrationUrl && program.registrationOpen && <a href={registrationUrl} className="mt-5 flex min-h-12 items-center justify-center rounded-xl bg-white px-5 font-bold text-emerald-900">Daftar Sekarang</a>}{contact && <a href={`https://wa.me/${contact}?text=${encodeURIComponent(`Halo ${program.contactName || "Admin TDA Pekanbaru"}, saya ingin bertanya tentang ${title}.`)}`} target="_blank" className="mt-3 flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/30 px-5 font-bold"><MessageCircle className="size-5"/>Hubungi {program.contactName || "Admin"}</a>}</section><a href={`https://wa.me/?text=${waText}`} target="_blank" className="flex min-h-12 items-center justify-center gap-2 rounded-2xl border bg-white px-5 font-bold text-emerald-800 shadow-sm"><Share2 className="size-5"/>Bagikan ke WhatsApp</a></aside></div>
    <footer className="border-t bg-white px-5 py-8 text-center text-sm text-slate-500">TDA Pekanbaru 9.0 · #RiangGembira</footer></main>;
}

function Info({ icon: Icon, label, value }: { icon: typeof CalendarDays; label: string; value: string }) { return <div className="flex gap-3 rounded-2xl bg-white/10 p-4"><Icon className="mt-0.5 size-5 shrink-0 text-emerald-300"/><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-300">{label}</p><p className="mt-1 text-sm font-semibold leading-5">{value}</p></div></div>; }
function PriceRow({ label, value }: { label: string; value: number | null }) { return <div className="flex items-center justify-between gap-4 rounded-xl bg-emerald-50 p-4"><span className="text-sm font-semibold text-slate-600">{label}</span><strong className="text-emerald-900">{value === null ? "Belum ditentukan" : value === 0 ? "Gratis" : rupiah(value)}</strong></div>; }
