import type { Metadata } from "next";
import Image from "next/image";
import { ArrowLeft, CalendarDays, CheckCircle2, MapPin, MessageCircle, Share2, Sparkles, TicketCheck, Users } from "lucide-react";
import { getPublicProgram } from "@/db/public-programs";
import { publicOrigin } from "@/lib/public-origin";
import { PublicShell } from "@/components/public-site/public-shell";

export const dynamic = "force-dynamic";
const origin = publicOrigin();
function dateLabel(value: string | null) { if (!value) return "Jadwal segera diumumkan"; return new Intl.DateTimeFormat("id-ID", { dateStyle: "long", timeZone: "Asia/Jakarta" }).format(new Date(`${value}T00:00:00+07:00`)); }
function titleOf(p: { publicTitle: string; programTitle: string }) { return p.publicTitle || p.programTitle; }
function rupiah(value: number | null) { return new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value || 0); }

export async function generateMetadata({ params }: { params: Promise<{ code: string }> }): Promise<Metadata> {
  try { const p = await getPublicProgram((await params).code); if (!p) return { title: "Program TDA Pekanbaru" }; const title = `${titleOf(p)} — TDA Pekanbaru`; const description = p.tagline || p.description || `Informasi Program ${titleOf(p)} dari TDA Pekanbaru.`; const image = p.flyerKey ? `${origin}/api/public-programs/${p.programCode}/flyer` : undefined; return { title, description, openGraph: { title, description, type: "website", locale: "id_ID", url: `${origin}/program/${p.programCode.toLowerCase()}`, images: image ? [{ url: image, alt: `Flyer ${titleOf(p)}` }] : [] }, twitter: { card: image ? "summary_large_image" : "summary", title, description, images: image ? [image] : [] } }; } catch { return { title: "Program TDA Pekanbaru" }; }
}

export default async function PublicProgramPage({ params }: { params: Promise<{ code: string }> }) {
  const program = await getPublicProgram((await params).code).catch(() => null);
  if (!program) return <PublicShell current="/program"><main data-testid="public-program-not-found" className="grid min-h-[60vh] place-items-center bg-tda-bg-soft p-6 text-center"><div><h1 className="tda-display text-[32px] leading-[1.1]">Program belum tersedia</h1><p className="mt-2 text-tda-muted">Program belum dipublikasikan atau tautannya tidak valid.</p><a href="/program" className="mt-6 inline-flex rounded-xl bg-tda-navy px-5 py-3 font-bold text-white">Lihat Program Lainnya</a></div></main></PublicShell>;
  const title = titleOf(program); const benefits = program.benefits.split("\n").map((x) => x.trim()).filter(Boolean); const registrationUrl = program.registrationEventId ? `/daftar/${program.registrationEventId}` : ""; const shareUrl = `${origin}/program/${program.programCode.toLowerCase()}`; const waText = encodeURIComponent(`*${title}*\n${program.tagline || "Program TDA Pekanbaru"}\n\nLihat informasi lengkap: ${shareUrl}`); const contact = program.contactPhone.replace(/^0/, "62").replace(/\D/g, "");
  return <PublicShell current="/program"><main className="bg-tda-bg-soft text-tda-ink" data-testid="public-program-detail-page"><nav aria-label="Breadcrumb" className="border-b border-[color:var(--tda-border)] bg-white"><div className="mx-auto flex max-w-6xl items-center px-5 py-2"><a href="/program" data-testid="program-detail-back-link" className="tda-focus inline-flex min-h-11 items-center gap-2 rounded-lg text-sm font-bold text-tda-indigo hover:text-tda-navy"><ArrowLeft className="size-4"/>Semua Program</a></div></nav>
    <section className="bg-tda-navy text-white"><div className="mx-auto grid max-w-6xl gap-8 px-5 py-10 lg:grid-cols-[.72fr_1fr] lg:items-center lg:py-14"><div className="overflow-hidden rounded-3xl bg-gradient-to-br from-tda-navy to-tda-indigo shadow-2xl">{program.flyerKey ? <div className="relative aspect-[4/5]"><Image src={`/api/public-programs/${program.programCode}/flyer`} alt={`Flyer ${title}`} fill priority sizes="(min-width: 1024px) 460px, 100vw" className="object-cover"/></div> : <div className="flex aspect-[4/5] flex-col justify-between p-8"><div className="flex items-center gap-2 font-bold text-tda-soft"><Sparkles className="size-5"/>TDA PEKANBARU 9.0</div><div><p className="text-sm font-bold text-tda-soft">{program.divisionName}</p><h2 className="tda-display mt-3 text-[40px] leading-[1.08]">{title}</h2></div><p className="text-sm font-bold tracking-widest text-tda-soft">#{program.programCode}</p></div>}</div><div><p className="text-sm font-bold uppercase tracking-[.18em] text-tda-soft">Program {program.divisionName}</p><h1 className="tda-display mt-4 text-[40px] leading-[1.06] sm:text-[56px]">{title}</h1><p className="mt-5 text-lg leading-8 text-[color:var(--tda-on-dark-muted)]">{program.tagline || "Belajar, bertumbuh, dan berkolaborasi bersama TDA Pekanbaru."}</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><Info icon={CalendarDays} label="Jadwal" value={dateLabel(program.eventDate || program.startDate)} /><Info icon={MapPin} label="Lokasi" value={program.eventLocation || "Segera diumumkan"} /><Info icon={Users} label="Penyelenggara" value={program.divisionName} /><Info icon={TicketCheck} label="Biaya" value={program.eventIsPaid ? "Program berbayar" : program.registrationEventId ? "Gratis" : "Lihat informasi program"} /></div><div className="mt-8 flex flex-col gap-3 sm:flex-row">{registrationUrl && program.registrationOpen ? <a href={registrationUrl} className="inline-flex min-h-12 items-center justify-center rounded-xl bg-white px-6 font-bold text-tda-navy">Daftar Sekarang</a> : <span className="inline-flex min-h-12 items-center justify-center rounded-xl bg-white/10 px-6 font-bold text-[color:var(--tda-on-dark-muted)]">{registrationUrl ? "Pendaftaran Ditutup" : "Pendaftaran Segera Dibuka"}</span>}<a href={`https://wa.me/?text=${waText}`} target="_blank" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/30 px-6 font-bold"><Share2 className="size-4"/>Bagikan</a></div></div></div></section>
    <div className="mx-auto grid max-w-6xl gap-6 px-5 py-10 lg:grid-cols-[1fr_.55fr]"><div className="space-y-6"><section className="rounded-3xl border bg-white p-6 shadow-sm sm:p-8"><h2 className="tda-display text-[30px] leading-[1.15]">Tentang Program</h2><p className="mt-4 whitespace-pre-wrap text-base leading-8 text-tda-muted">{program.description || program.tagline || "Informasi lengkap program akan segera diperbarui oleh penyelenggara."}</p></section>{benefits.length > 0 && <section className="rounded-3xl border bg-white p-6 shadow-sm sm:p-8"><h2 className="tda-display text-[30px] leading-[1.15]">Manfaat yang Didapat</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{benefits.map((benefit) => <div key={benefit} className="flex gap-3 rounded-xl bg-tda-bg-tint p-4"><CheckCircle2 className="mt-0.5 size-5 shrink-0 text-tda-indigo"/><p className="leading-6">{benefit}</p></div>)}</div></section>}</div><aside className="space-y-6">{Boolean(program.eventIsPaid) && <section className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="font-semibold">Harga Pendaftaran</h2><div className="mt-4 grid gap-3"><PriceRow label="Member TDA" value={program.memberPrice}/><PriceRow label="Umum" value={program.publicPrice}/></div></section>}{program.audience && <section className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="font-semibold">Program Ini Cocok Untuk</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-tda-muted">{program.audience}</p></section>}<section className="rounded-3xl bg-tda-navy p-6 text-white"><h2 className="text-xl font-semibold">{registrationUrl && program.registrationOpen ? "Pendaftaran Dibuka" : registrationUrl ? "Pendaftaran Ditutup" : "Informasi Pendaftaran"}</h2><p className="mt-3 text-sm leading-6 text-[color:var(--tda-on-dark-muted)]">{registrationUrl && program.registrationOpen ? "Amankan tempat Anda melalui formulir resmi TDA Pekanbaru." : "Hubungi narahubung untuk informasi lebih lanjut mengenai program ini."}</p>{registrationUrl && program.registrationOpen && <a href={registrationUrl} className="mt-5 flex min-h-12 items-center justify-center rounded-xl bg-white px-5 font-bold text-tda-navy">Daftar Sekarang</a>}{contact && <a href={`https://wa.me/${contact}?text=${encodeURIComponent(`Halo ${program.contactName || "Admin TDA Pekanbaru"}, saya ingin bertanya tentang ${title}.`)}`} target="_blank" className="mt-3 flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/30 px-5 font-bold"><MessageCircle className="size-5"/>Hubungi {program.contactName || "Admin"}</a>}</section><a href={`https://wa.me/?text=${waText}`} target="_blank" className="flex min-h-12 items-center justify-center gap-2 rounded-2xl border bg-white px-5 font-bold text-tda-indigo shadow-sm"><Share2 className="size-5"/>Bagikan ke WhatsApp</a></aside></div>
    </main></PublicShell>;
}

function Info({ icon: Icon, label, value }: { icon: typeof CalendarDays; label: string; value: string }) { return <div className="flex gap-3 rounded-2xl bg-white/10 p-4"><Icon className="mt-0.5 size-5 shrink-0 text-tda-soft"/><div><p className="text-xs font-bold uppercase tracking-wider text-tda-soft">{label}</p><p className="mt-1 text-sm font-semibold leading-5">{value}</p></div></div>; }
function PriceRow({ label, value }: { label: string; value: number | null }) { return <div className="flex items-center justify-between gap-4 rounded-xl bg-tda-bg-tint p-4"><span className="text-sm font-semibold text-tda-muted">{label}</span><strong className="text-tda-navy">{value === null ? "Belum ditentukan" : value === 0 ? "Gratis" : rupiah(value)}</strong></div>; }
