"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, LoaderCircle } from "lucide-react";

type Question = { id: number; question: string; questionType: string; optionsJson: string; isRequired: number };
type Data = { participant: { name: string; eventName: string; programTitle: string; feedbackOpen: number }; questions: Question[]; answers: { questionId: number | null; answerJson: string | null }[] };

export default function FeedbackForm({ token }: { token: string }) {
  const [data, setData] = useState<Data | null>(null); const [answers, setAnswers] = useState<Record<string, string | string[]>>({});
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [done, setDone] = useState(false); const [error, setError] = useState("");
  useEffect(() => { fetch(`/api/public-feedback/${token}`).then(async (r) => { const p = await r.json(); if (!r.ok) throw new Error(p.error); setData(p); const initial: Record<string, string | string[]> = {}; p.answers.forEach((a: { questionId: number; answerJson: string }) => { if (!a.questionId) return; try { initial[String(a.questionId)] = JSON.parse(a.answerJson); } catch { initial[String(a.questionId)] = a.answerJson; } }); setAnswers(initial); }).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, [token]);
  async function submit() { setSaving(true); setError(""); try { const r = await fetch(`/api/public-feedback/${token}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ answers }) }); const p = await r.json(); if (!r.ok) throw new Error(p.error); setDone(true); } catch (e) { setError(e instanceof Error ? e.message : "Feedback belum dapat disimpan."); } finally { setSaving(false); } }
  if (loading) return <main className="grid min-h-screen place-items-center bg-emerald-50"><LoaderCircle className="animate-spin text-emerald-700" /></main>;
  if (error && !data) return <main className="grid min-h-screen place-items-center bg-emerald-50 p-6 text-center"><p>{error}</p></main>;
  if (!data) return null;
  if (done) return <main className="grid min-h-screen place-items-center bg-emerald-50 p-6"><div className="max-w-md rounded-3xl bg-white p-8 text-center shadow-xl"><CheckCircle2 className="mx-auto size-14 text-emerald-600"/><h1 className="mt-4 text-2xl font-bold">Terima kasih</h1><p className="mt-2 text-muted-foreground">Feedback Anda berhasil disimpan dan akan menjadi bahan evaluasi program.</p></div></main>;
  return <main className="min-h-screen bg-emerald-50 p-4 sm:p-8"><div className="mx-auto max-w-2xl overflow-hidden rounded-3xl bg-white shadow-xl"><header className="bg-[#102d20] p-6 text-white"><p className="text-sm text-emerald-200">FEEDBACK PROGRAM TDA PEKANBARU</p><h1 className="mt-2 text-2xl font-bold">{data.participant.programTitle}</h1><p className="mt-2 text-sm text-emerald-100">{data.participant.eventName} · {data.participant.name}</p></header><div className="space-y-5 p-6">{!data.participant.feedbackOpen ? <p className="rounded-xl bg-amber-50 p-4 text-amber-900">Form feedback belum dibuka oleh panitia.</p> : data.questions.length === 0 ? <p className="text-muted-foreground">Pertanyaan feedback belum disiapkan.</p> : data.questions.map((q, index) => <QuestionField key={q.id} q={q} index={index} value={answers[String(q.id)]} onChange={(value) => setAnswers({ ...answers, [String(q.id)]: value })} />)}{error && <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{data.participant.feedbackOpen && data.questions.length > 0 && <button onClick={submit} disabled={saving} className="h-12 w-full rounded-xl bg-emerald-700 font-bold text-white disabled:opacity-50">{saving ? "Menyimpan…" : "Kirim Feedback"}</button>}</div></div></main>;
}

function QuestionField({ q, index, value, onChange }: { q: Question; index: number; value: string | string[] | undefined; onChange: (value: string | string[]) => void }) {
  let options: string[] = []; try { options = JSON.parse(q.optionsJson); } catch {}
  return <div><label className="mb-2 block font-semibold">{index + 1}. {q.question}{q.isRequired ? " *" : ""}</label>{q.questionType === "rating" ? <div className="grid grid-cols-5 gap-2">{[1,2,3,4,5].map((n) => <button key={n} type="button" onClick={() => onChange(String(n))} className={`h-11 rounded-xl border font-bold ${value === String(n) ? "border-emerald-700 bg-emerald-700 text-white" : "bg-white"}`}>{n}</button>)}</div> : q.questionType === "select" ? <select value={String(value || "")} onChange={(e) => onChange(e.target.value)} className="h-11 w-full rounded-xl border bg-white px-3"><option value="">Pilih jawaban</option>{options.map((o) => <option key={o}>{o}</option>)}</select> : q.questionType === "checklist" ? <div className="space-y-2">{options.map((o) => <label key={o} className="flex items-center gap-2"><input type="checkbox" checked={Array.isArray(value) && value.includes(o)} onChange={(e) => { const current = Array.isArray(value) ? value : []; onChange(e.target.checked ? [...current, o] : current.filter((v) => v !== o)); }} />{o}</label>)}</div> : q.questionType === "paragraph" ? <textarea value={String(value || "")} onChange={(e) => onChange(e.target.value)} rows={4} className="w-full rounded-xl border p-3" /> : <input value={String(value || "")} onChange={(e) => onChange(e.target.value)} className="h-11 w-full rounded-xl border px-3" />}</div>;
}
