"use client";

import Image from "next/image";
import { useMemo, useState } from "react";
import { ArrowRight, CalendarDays, MapPin, TicketCheck } from "lucide-react";
import type { PublicProgramCard } from "@/components/public-program-catalog";

function eventDate(item: PublicProgramCard) { return item.eventDate || item.startDate; }
function monthKey(value: string) { return value ? value.slice(0, 7) : ""; }
function dateLabel(value: string) { if (!value) return "Jadwal segera diumumkan"; return new Intl.DateTimeFormat("id-ID", { weekday: "short", day: "numeric", month: "long", year: "numeric", timeZone: "Asia/Jakarta" }).format(new Date(`${value}T00:00:00+07:00`)); }
function priceLabel(item: PublicProgramCard) { if (!item.registrationEventId && item.eventIsPaid === null) return "Informasi di halaman detail"; if (!item.eventIsPaid) return "Gratis"; const values=[item.publicPrice,item.memberPrice].filter((v):v is number=>typeof v==="number"&&v>0); return values.length ? `Mulai ${new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Math.min(...values))}` : "Berbayar"; }

export default function PublicCalendar({ programs }: { programs: PublicProgramCard[] }) {
  const months = useMemo(() => [...new Set(programs.map((p) => monthKey(eventDate(p))).filter(Boolean))].sort(), [programs]);
  const [month, setMonth] = useState(months.find((m) => m >= new Date().toISOString().slice(0,7)) || months[0] || "all");
  const [division, setDivision] = useState("all"); const [payment, setPayment] = useState("all");
  const divisions = [...new Set(programs.map((p) => p.divisionName))];
  const filtered = programs.filter((p) => (month === "all" || monthKey(eventDate(p)) === month) && (division === "all" || p.divisionName === division) && (payment === "all" || (payment === "free" ? !p.eventIsPaid : Boolean(p.eventIsPaid)))).sort((a,b) => eventDate(a).localeCompare(eventDate(b)));
  return <><section className="rounded-2xl border bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-3"><select value={month} onChange={(e)=>setMonth(e.target.value)} className="h-11 rounded-xl border bg-white px-3 text-sm"><option value="all">Semua bulan</option>{months.map((m)=><option key={m} value={m}>{new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric",timeZone:"Asia/Jakarta"}).format(new Date(`${m}-01T00:00:00+07:00`))}</option>)}</select><select value={division} onChange={(e)=>setDivision(e.target.value)} className="h-11 rounded-xl border bg-white px-3 text-sm"><option value="all">Semua divisi</option>{divisions.map((d)=><option key={d}>{d}</option>)}</select><select value={payment} onChange={(e)=>setPayment(e.target.value)} className="h-11 rounded-xl border bg-white px-3 text-sm"><option value="all">Gratis dan berbayar</option><option value="free">Gratis</option><option value="paid">Berbayar</option></select></div></section><section className="mt-6 space-y-4">{filtered.map((program)=><a key={program.programCode} href={`/program/${program.programCode.toLowerCase()}`} className="group grid gap-4 rounded-3xl border bg-white p-5 shadow-sm transition hover:border-[color:var(--tda-border-strong)] hover:shadow-lg sm:grid-cols-[150px_1fr_auto] sm:items-center"><div className="overflow-hidden rounded-2xl bg-gradient-to-br from-tda-navy to-tda-indigo"><div className="relative flex aspect-[16/10] items-center justify-center text-white">{program.flyerKey ? <Image src={`/api/public-programs/${program.programCode}/flyer`} alt="" fill sizes="(min-width: 640px) 150px, 100vw" className="object-cover object-top"/> : <CalendarDays className="size-9"/>}</div></div><div><p className="text-xs font-bold uppercase tracking-wider text-tda-indigo">{program.divisionName}</p><h2 className="mt-1 text-xl font-bold">{program.publicTitle || program.programTitle}</h2><p className="mt-2 flex items-center gap-2 text-sm text-tda-muted"><CalendarDays className="size-4 text-tda-indigo"/>{dateLabel(eventDate(program))}</p><p className="mt-1 flex items-center gap-2 text-sm text-tda-muted"><MapPin className="size-4 text-tda-indigo"/>{program.eventLocation || "Lokasi segera diumumkan"}</p><p className="mt-1 flex items-center gap-2 text-sm font-semibold text-tda-indigo"><TicketCheck className="size-4"/>{priceLabel(program)}</p></div><span className="inline-flex items-center gap-1 font-bold text-tda-indigo">Detail<ArrowRight className="size-4 transition group-hover:translate-x-1"/></span></a>)}</section>{!filtered.length&&<div className="mt-6 rounded-3xl border bg-white p-12 text-center"><p className="font-bold">Belum ada kegiatan pada pilihan ini</p><p className="mt-2 text-sm text-slate-500">Coba pilih bulan atau filter yang berbeda.</p></div>}</>;
}
