"use client";

import Image from "next/image";
import { useMemo, useState } from "react";
import { ArrowRight, CalendarDays, MapPin, Search, Sparkles } from "lucide-react";
import { Input } from "@/components/ui/input";

export type PublicProgramCard = { programCode: string; publicTitle: string; programTitle: string; tagline: string; divisionName: string; startDate: string; endDate: string; eventDate: string | null; eventLocation: string | null; registrationEventId: number | null; registrationOpen: number | null; eventIsPaid: number | null; publicPrice: number | null; memberPrice: number | null; isFeatured: number; flyerKey: string | null };

function statusOf(item: PublicProgramCard) { const today = new Date().toISOString().slice(0,10); const start = item.eventDate || item.startDate; if (item.endDate && item.endDate < today) return "Selesai"; if (start && start > today) return item.registrationOpen ? "Pendaftaran Dibuka" : "Akan Datang"; return item.registrationOpen ? "Pendaftaran Dibuka" : "Sedang Berjalan"; }
function dateLabel(value: string | null) { if (!value) return "Jadwal segera diumumkan"; return new Intl.DateTimeFormat("id-ID", { dateStyle: "long", timeZone: "Asia/Jakarta" }).format(new Date(`${value}T00:00:00+07:00`)); }
function priceLabel(item: PublicProgramCard) { if (!item.registrationEventId && item.eventIsPaid === null) return "Lihat detail program"; if (!item.eventIsPaid) return "Gratis"; const values = [item.memberPrice, item.publicPrice].filter((v): v is number => typeof v === "number" && v > 0); return values.length ? `Mulai ${new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(Math.min(...values))}` : "Berbayar"; }

export default function PublicProgramCatalog({ programs }: { programs: PublicProgramCard[] }) {
  const [search, setSearch] = useState(""); const [division, setDivision] = useState("all"); const [status, setStatus] = useState("all");
  const divisions = [...new Set(programs.map((p) => p.divisionName))];
  const filtered = useMemo(() => programs.filter((p) => { const q = search.trim().toLowerCase(); const current = statusOf(p); return (!q || `${p.publicTitle} ${p.programTitle} ${p.tagline} ${p.divisionName}`.toLowerCase().includes(q)) && (division === "all" || p.divisionName === division) && (status === "all" || current === status); }), [division, programs, search, status]);
  return <><section className="rounded-2xl border bg-white p-4 shadow-sm"><div className="grid gap-3 lg:grid-cols-[1fr_220px_220px]"><label className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Cari program atau kegiatan…" className="pl-9" /></label><select value={division} onChange={(e) => setDivision(e.target.value)} className="h-10 rounded-md border bg-white px-3 text-sm"><option value="all">Semua divisi</option>{divisions.map((d) => <option key={d}>{d}</option>)}</select><select value={status} onChange={(e) => setStatus(e.target.value)} className="h-10 rounded-md border bg-white px-3 text-sm"><option value="all">Semua status</option>{["Pendaftaran Dibuka","Akan Datang","Sedang Berjalan","Selesai"].map((s) => <option key={s}>{s}</option>)}</select></div></section>
    <section className="mt-6 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{filtered.map((program) => { const current = statusOf(program); return <a key={program.programCode} href={`/program/${program.programCode.toLowerCase()}`} className="group overflow-hidden rounded-3xl border bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="relative aspect-[4/5] overflow-hidden bg-gradient-to-br from-tda-navy via-tda-indigo to-tda-violet">{program.flyerKey ? <Image src={`/api/public-programs/${program.programCode}/flyer`} alt={`Flyer ${program.publicTitle || program.programTitle}`} fill sizes="(min-width: 1280px) 400px, (min-width: 640px) 50vw, 100vw" className="object-cover"/> : <div className="flex size-full flex-col justify-between p-7 text-white"><div className="flex items-center gap-2 text-sm font-bold text-tda-soft"><Sparkles className="size-5"/>TDA PEKANBARU 9.0</div><div><p className="text-sm font-semibold text-tda-soft">{program.divisionName}</p><h2 className="tda-display mt-3 text-[34px] leading-[1.1]">{program.publicTitle || program.programTitle}</h2><p className="mt-3 leading-6 text-[color:var(--tda-on-dark-muted)]">{program.tagline || "Tumbuh dan berkolaborasi bersama ekosistem TDA Pekanbaru."}</p></div><p className="text-xs font-bold tracking-widest text-tda-soft">#{program.programCode}</p></div>}<span className={`absolute left-4 top-4 rounded-full px-3 py-1.5 text-xs font-bold shadow ${current === "Pendaftaran Dibuka" ? "bg-white text-tda-navy" : current === "Selesai" ? "bg-slate-100 text-slate-700" : "bg-amber-300 text-amber-950"}`}>{current}</span>{program.isFeatured ? <span className="absolute right-4 top-4 rounded-full bg-white px-3 py-1.5 text-xs font-bold text-tda-indigo shadow">Unggulan</span> : null}</div><div className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-tda-indigo">{program.divisionName}</p><h2 className="mt-2 text-xl font-semibold leading-tight">{program.publicTitle || program.programTitle}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-tda-muted">{program.tagline || "Temukan manfaat dan informasi lengkap program ini."}</p><div className="mt-4 space-y-2 border-t pt-4 text-sm text-tda-muted"><p className="flex items-center gap-2"><CalendarDays className="size-4 text-tda-indigo"/>{dateLabel(program.eventDate || program.startDate)}</p><p className="flex items-center gap-2"><MapPin className="size-4 text-tda-indigo"/>{program.eventLocation || "Informasi lokasi di halaman detail"}</p></div><div className="mt-5 flex items-center justify-between"><strong className="text-sm text-tda-indigo">{priceLabel(program)}</strong><span className="flex items-center gap-1 text-sm font-bold text-tda-indigo">Lihat Program <ArrowRight className="size-4 transition group-hover:translate-x-1"/></span></div></div></a>; })}</section>
    {!filtered.length && <div className="mt-6 rounded-3xl border bg-white p-12 text-center"><p className="font-bold">Program belum ditemukan</p><p className="mt-2 text-sm text-slate-500">Coba ubah kata pencarian atau filter.</p></div>}</>;
}
