"use client";

import { useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, HelpCircle, LayoutDashboard, MousePointerClick, RotateCcw, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Progress } from "@/components/ui/progress";

type DashboardData = {
  summary: { total: number; pendingApproval: number; approved: number; revisionRequired: number; rejected: number; totalTasks: number; completedTasks: number; overdueTasks: number; averageProgress: number };
  divisions: { id: number; code: string; name: string; totalPrograms: number; completedPrograms: number }[];
  period: { name: string } | null;
  nextProgramCode: string;
};

const steps = [
  { title: "Mengenal Dashboard", description: "Dashboard adalah pusat pemantauan seluruh Program Kerja. Dari halaman ini, pengurus dapat melihat kondisi organisasi tanpa membuka program satu per satu.", visual: "overview" },
  { title: "Ringkasan Program Kerja", description: "Kartu bagian atas menunjukkan jumlah program menurut statusnya. Gunakan informasi ini untuk melihat program yang masih menunggu keputusan atau membutuhkan revisi.", visual: "status" },
  { title: "Progres dan Tugas", description: "Rata-rata progres dihitung dari penyelesaian breakdown pekerjaan. Tugas terlambat adalah pekerjaan yang melewati due date dan belum berstatus Selesai.", visual: "progress" },
  { title: "Pantau Setiap Divisi", description: "Setiap kartu divisi menampilkan total program, program selesai, dan program yang masih tersisa.", visual: "division" },
  { title: "Buka Program Divisi", description: "Klik kartu divisi untuk masuk ke menu Program Kerja. Filter divisi akan langsung aktif sehingga hanya program divisi tersebut yang tampil.", visual: "click" },
  { title: "Periode dan Kode Program", description: "Periode aktif menentukan periode kepengurusan yang digunakan. Kode program berikutnya dibuat otomatis agar setiap program memiliki identitas yang berbeda.", visual: "period" },
  { title: "Pembaruan Data", description: "Dashboard memperbarui informasi secara otomatis saat halaman terbuka. Jika browser di-refresh, aplikasi akan kembali ke menu terakhir yang digunakan.", visual: "refresh" },
] as const;

export default function DashboardGuide({ data }: { data: DashboardData }) {
  const [open, setOpen] = useState(false); const [step, setStep] = useState(0);
  const current = steps[step];
  function close() { setOpen(false); window.localStorage.setItem("tdapku-dashboard-guide-seen", "1"); }
  return <><Button type="button" variant="outline" onClick={() => { setStep(0); setOpen(true); }} className="shrink-0"><HelpCircle className="size-4"/>Petunjuk</Button>
    <Dialog open={open} onOpenChange={(next) => { if (!next) close(); else setOpen(true); }}><DialogContent className="h-[100dvh] max-h-none w-screen max-w-none overflow-y-auto rounded-none border-0 p-0 sm:h-auto sm:max-h-[92vh] sm:w-[calc(100vw-2rem)] sm:max-w-5xl sm:rounded-3xl sm:border"><DialogHeader className="sticky top-0 z-10 border-b bg-white px-5 py-4 text-left sm:px-7"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-700">Petunjuk Dashboard · Langkah {step + 1} dari {steps.length}</p><DialogTitle className="mt-1 text-xl sm:text-2xl">{current.title}</DialogTitle></div><button onClick={close} className="grid size-10 shrink-0 place-items-center rounded-full bg-slate-100" aria-label="Tutup petunjuk"><X className="size-5"/></button></div><DialogDescription className="sr-only">Panduan penggunaan menu Dashboard tdapku.</DialogDescription><Progress value={(step + 1) / steps.length * 100} className="mt-3"/></DialogHeader>
      <div className="grid gap-6 p-5 sm:p-7 lg:grid-cols-[1.35fr_.65fr] lg:items-center"><GuideVisual kind={current.visual} data={data}/><div><div className="rounded-2xl bg-emerald-50 p-5"><div className="grid size-10 place-items-center rounded-xl bg-emerald-700 font-bold text-white">{step + 1}</div><p className="mt-4 text-base leading-7 text-emerald-950">{current.description}</p></div><div className="mt-4 rounded-2xl border p-4"><p className="text-sm font-bold">Yang perlu dilakukan</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{instructionFor(current.visual)}</p></div></div></div>
      <div className="sticky bottom-0 flex items-center justify-between gap-3 border-t bg-white px-5 py-4 sm:px-7"><Button variant="outline" disabled={step === 0} onClick={() => setStep((value) => Math.max(0, value - 1))}><ArrowLeft/>Sebelumnya</Button><div className="hidden gap-1.5 sm:flex">{steps.map((_, index) => <button key={index} onClick={() => setStep(index)} aria-label={`Langkah ${index + 1}`} className={`size-2.5 rounded-full ${index === step ? "bg-emerald-700" : "bg-slate-200"}`}/>)}</div>{step < steps.length - 1 ? <Button onClick={() => setStep((value) => Math.min(steps.length - 1, value + 1))}>Selanjutnya<ArrowRight/></Button> : <Button onClick={close}><CheckCircle2/>Selesai</Button>}</div>
    </DialogContent></Dialog></>;
}

function GuideVisual({ kind, data }: { kind: typeof steps[number]["visual"]; data: DashboardData }) {
  const division = data.divisions[0] ?? { code: "EDU", name: "Edukasi", totalPrograms: 0, completedPrograms: 0 };
  const remaining = Math.max(0, division.totalPrograms - division.completedPrograms);
  return <div className="relative overflow-hidden rounded-2xl border bg-[#f5f8f5] p-3 shadow-inner sm:p-5"><div className="mb-3 flex items-center gap-2 rounded-xl bg-[#102d20] p-3 text-white"><LayoutDashboard className="size-5"/><strong className="text-sm">Dashboard Program Kerja</strong></div>
    {kind === "overview" && <div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><MiniCard label="Total Program" value={data.summary.total} marker={1}/><MiniCard label="Menunggu Approval" value={data.summary.pendingApproval} marker={2}/><MiniCard label="Disetujui" value={data.summary.approved} marker={3}/><MiniCard label="Tugas Terlambat" value={data.summary.overdueTasks} marker={4}/></div>}
    {kind === "status" && <div className="grid grid-cols-2 gap-3"><MiniCard label="Menunggu Approval" value={data.summary.pendingApproval} marker={1} tone="amber"/><MiniCard label="Disetujui" value={data.summary.approved} marker={2}/><MiniCard label="Perlu Revisi" value={data.summary.revisionRequired} marker={3} tone="blue"/><MiniCard label="Ditolak" value={data.summary.rejected} marker={4} tone="rose"/></div>}
    {kind === "progress" && <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border-2 border-emerald-600 bg-white p-4"><div className="flex justify-between"><span className="text-sm font-bold">Rata-rata Progres</span><strong>{data.summary.averageProgress}%</strong></div><Progress value={data.summary.averageProgress} className="mt-4"/><p className="mt-3 text-xs text-muted-foreground">{data.summary.completedTasks}/{data.summary.totalTasks} tugas selesai</p></div><div className="rounded-xl border-2 border-amber-500 bg-white p-4"><Clock3 className="size-7 text-amber-600"/><p className="mt-3 text-3xl font-bold">{data.summary.overdueTasks}</p><p className="text-sm text-muted-foreground">Tugas Terlambat</p></div></div>}
    {(kind === "division" || kind === "click") && <div className="relative rounded-xl border-2 border-emerald-600 bg-white p-4"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-emerald-50 text-xs font-bold text-emerald-800">{division.code}</span><strong>{division.name}</strong></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><Metric label="Program" value={division.totalPrograms}/><Metric label="Selesai" value={division.completedPrograms}/><Metric label="Sisa" value={remaining}/></div>{kind === "click" && <div className="absolute right-3 top-3 animate-pulse rounded-full bg-amber-400 p-2 text-amber-950 shadow-lg"><MousePointerClick className="size-5"/></div>}</div>}
    {kind === "period" && <div className="rounded-xl bg-[#153323] p-5 text-white"><p className="text-sm text-emerald-200">Periode aktif</p><h3 className="mt-2 text-xl font-bold">{data.period?.name ?? "TDA Pekanbaru 9.0 · 2026–2029"}</h3><div className="mt-5 rounded-xl bg-white/10 p-3"><p className="text-xs text-emerald-200">Format ID program</p><p className="mt-1 font-mono text-lg font-bold">{data.nextProgramCode}</p></div></div>}
    {kind === "refresh" && <div className="grid min-h-48 place-items-center rounded-xl bg-white"><div className="text-center"><span className="mx-auto grid size-16 place-items-center rounded-full bg-emerald-50 text-emerald-700"><RotateCcw className="size-8"/></span><p className="mt-4 font-bold">Data diperbarui otomatis</p><p className="mt-1 text-sm text-muted-foreground">Menu terakhir tetap tersimpan</p></div></div>}
  </div>;
}

function MiniCard({ label, value, marker, tone = "green" }: { label: string; value: number; marker: number; tone?: string }) { const tones: Record<string,string> = { green: "border-emerald-500 bg-emerald-50", amber: "border-amber-500 bg-amber-50", blue: "border-blue-500 bg-blue-50", rose: "border-rose-500 bg-rose-50" }; return <div className={`relative min-h-28 rounded-xl border-2 p-3 ${tones[tone]}`}><span className="absolute -right-2 -top-2 grid size-7 place-items-center rounded-full bg-[#102d20] text-xs font-bold text-white">{marker}</span><p className="text-2xl font-bold">{value}</p><p className="mt-3 text-xs font-semibold">{label}</p></div>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-lg bg-slate-50 p-2"><strong className="block">{value}</strong><span className="text-xs text-muted-foreground">{label}</span></div>; }
function instructionFor(kind: typeof steps[number]["visual"]) { return ({ overview: "Gunakan kartu ringkasan untuk mendapatkan gambaran kondisi Program Kerja saat ini.", status: "Prioritaskan program berstatus Menunggu Approval dan Perlu Revisi.", progress: "Periksa tugas terlambat, lalu buka Program Kerja atau Kalender untuk menindaklanjutinya.", division: "Bandingkan jumlah Program, Selesai, dan Sisa pada masing-masing divisi.", click: "Tekan kartu divisi yang ingin diperiksa. Aplikasi akan membuka daftar Program Kerja yang sudah terfilter.", period: "Pastikan kegiatan dicatat pada periode kepengurusan aktif. Kode program dibuat otomatis oleh sistem.", refresh: "Biarkan halaman terbuka untuk menerima pembaruan. Refresh manual tetap mengembalikan Anda ke menu terakhir." } as Record<string,string>)[kind]; }
