"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Bell, CheckCheck, CheckCircle2, Clock3, FileClock, History, LoaderCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { getCachedJson, invalidateClientCache } from "@/lib/client-cache";

type Notice = { id: number; programId: number | null; type: string; title: string; message: string; isRead: number; createdAt: string; programCode: string | null; programTitle: string | null };
type Activity = { id: number; action: string; description: string; createdAt: string; actorName: string; programCode: string | null; programTitle: string | null; divisionName: string | null };
type CenterData = { notifications: Notice[]; unreadCount: number; activities: Activity[]; hasMoreNotifications: boolean; hasMoreActivities: boolean };

function dateTime(value: string) { const normalized = value.includes("T") ? value : `${value.replace(" ", "T")}Z`; return new Intl.DateTimeFormat("id-ID", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Jakarta" }).format(new Date(normalized)); }
const iconByType: Record<string, typeof Bell> = { overdue: AlertTriangle, deadline: Clock3, approval: FileClock, revision: AlertTriangle, rejected: AlertTriangle, approved: CheckCircle2, lpj: FileClock, lpj_complete: CheckCircle2 };

export default function NotificationCenter({ onUnreadChange }: { onUnreadChange: (count: number) => void }) {
  const [data, setData] = useState<CenterData>({ notifications: [], unreadCount: 0, activities: [], hasMoreNotifications: false, hasMoreActivities: false }); const [loading, setLoading] = useState(true); const [loadingMore, setLoadingMore] = useState(false); const [onlyUnread, setOnlyUnread] = useState(false); const [type, setType] = useState("all"); const [notificationLimit, setNotificationLimit] = useState(30); const [activityLimit, setActivityLimit] = useState(50);
  async function load(nextNotificationLimit = notificationLimit, nextActivityLimit = activityLimit) { const payload = await getCachedJson<CenterData>(`/api/notifications?notification_limit=${nextNotificationLimit}&activity_limit=${nextActivityLimit}`, 15_000, true); setData(payload); onUnreadChange(payload.unreadCount); }
  useEffect(() => { let cancelled = false; getCachedJson<CenterData>("/api/notifications?notification_limit=30&activity_limit=50", 15_000).then((payload) => { if (!cancelled) { setData(payload); onUnreadChange(payload.unreadCount); } }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [onUnreadChange]);
  const notices = useMemo(() => data.notifications.filter((item) => (!onlyUnread || !item.isRead) && (type === "all" || item.type === type)), [data.notifications, onlyUnread, type]);
  async function mark(id?: number) { await fetch(id ? `/api/notifications/${id}` : "/api/notifications", { method: "PATCH" }); invalidateClientCache("/api/notifications"); await load(); }
  async function showMore(kind: "notifications" | "activities") { setLoadingMore(true); try { const nextNotificationLimit = kind === "notifications" ? Math.min(notificationLimit + 30, 100) : notificationLimit; const nextActivityLimit = kind === "activities" ? Math.min(activityLimit + 50, 150) : activityLimit; setNotificationLimit(nextNotificationLimit); setActivityLimit(nextActivityLimit); await load(nextNotificationLimit, nextActivityLimit); } finally { setLoadingMore(false); } }
  if (loading) return <div className="grid min-h-72 place-items-center"><LoaderCircle className="animate-spin text-primary" /></div>;
  return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-primary">Tahap 8</p><h1 className="mt-2 text-2xl font-bold sm:text-3xl">Notifikasi & Riwayat Aktivitas</h1><p className="mt-2 text-sm text-muted-foreground">Pantau tindak lanjut dan jejak perubahan Program Kerja.</p></div>{data.unreadCount > 0 && <Button variant="outline" onClick={() => mark()}><CheckCheck className="size-4" />Tandai semua dibaca</Button>}</div>
    <Tabs defaultValue="notifications"><TabsList><TabsTrigger value="notifications">Notifikasi <Badge variant="secondary" className="ml-2">{data.unreadCount}</Badge></TabsTrigger><TabsTrigger value="activities">Riwayat Aktivitas</TabsTrigger></TabsList>
      <TabsContent value="notifications" className="mt-4"><section className="rounded-2xl border bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={onlyUnread} onChange={(event) => setOnlyUnread(event.target.checked)} />Belum dibaca saja</label><select value={type} onChange={(event) => setType(event.target.value)} className="h-9 rounded-md border bg-white px-3 text-sm"><option value="all">Semua jenis</option><option value="approval">Approval</option><option value="approved">Disetujui</option><option value="revision">Revisi</option><option value="deadline">Tenggat</option><option value="overdue">Terlambat</option><option value="lpj">LPJ</option></select></div><div className="divide-y">{notices.length === 0 ? <p className="p-10 text-center text-sm text-muted-foreground">Tidak ada notifikasi sesuai filter.</p> : notices.map((item) => { const Icon = iconByType[item.type] ?? Bell; return <button key={item.id} type="button" onClick={() => { if (!item.isRead) mark(item.id); }} className={`flex w-full gap-4 p-4 text-left hover:bg-muted/30 ${item.isRead ? "opacity-70" : "bg-emerald-50/30"}`}><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-secondary text-primary"><Icon className="size-5" /></span><span className="min-w-0 flex-1"><span className="flex items-start justify-between gap-3"><strong>{item.title}</strong>{!item.isRead && <span className="mt-1 size-2 rounded-full bg-emerald-500" />}</span><span className="mt-1 block text-sm text-muted-foreground">{item.message}</span><span className="mt-2 block text-xs text-muted-foreground">{dateTime(item.createdAt)}</span></span></button>; })}</div>{data.hasMoreNotifications && <div className="border-t p-4 text-center"><Button variant="outline" disabled={loadingMore} onClick={() => showMore("notifications")}>{loadingMore && <LoaderCircle className="size-4 animate-spin" />}Tampilkan lebih banyak</Button></div>}</section></TabsContent>
      <TabsContent value="activities" className="mt-4"><section className="rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><div className="flex items-center gap-2"><History className="size-5 text-primary" /><h2 className="font-bold">Jejak Perubahan</h2></div></div><div className="divide-y">{data.activities.length === 0 ? <p className="p-10 text-center text-sm text-muted-foreground">Belum ada aktivitas Program Kerja.</p> : data.activities.map((item) => <article key={item.id} className="flex gap-4 p-4"><span className="mt-1 size-2 shrink-0 rounded-full bg-emerald-500" /><div><p className="text-sm font-medium">{item.description}</p><p className="mt-1 text-xs text-muted-foreground">{item.actorName} · {item.divisionName || "Organisasi"} · {dateTime(item.createdAt)}</p>{item.programCode && <Badge variant="secondary" className="mt-2">{item.programCode}</Badge>}</div></article>)}</div>{data.hasMoreActivities && <div className="border-t p-4 text-center"><Button variant="outline" disabled={loadingMore} onClick={() => showMore("activities")}>{loadingMore && <LoaderCircle className="size-4 animate-spin" />}Tampilkan lebih banyak</Button></div>}</section></TabsContent>
    </Tabs></div>;
}
