"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import QRCode from "qrcode";
import Image from "next/image";
import { BarChart3, Copy, Download, Eye, MessageSquareText, Plus, QrCode, Search, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import ProgramPublication from "@/components/program-management/program-publication";
import { publicOrigin as getPublicOrigin } from "@/lib/public-origin";

type Question = { id: number; question: string; questionType: string; optionsJson: string; isRequired: number };
type EventRow = { id: number; name: string; feedbackOpen: number; participantCount: number; responseCount: number };
type Payload = { questions: Question[]; events: EventRow[]; stats: { responseCount: number; averageRating: number; registeredCount: number; attendedCount: number; realizedIncome: number; realizedExpense: number } };
type ResultRow = { participantId: number; participantName: string; phone: string; eventId: number; eventName: string; submittedAt: string | null; questionId: number | null; answerJson: string | null };
type ParticipantResult = { participantId: number; participantName: string; phone: string; eventName: string; submittedAt: string | null; answers: Record<number, string> };

const publicOrigin = getPublicOrigin();

export default function ProgramFeedback(props: { programId: number; canManage: boolean }) {
  return <><ProgramFeedbackContent {...props} />{props.canManage && <ProgramPublication programId={props.programId} canManage />}</>;
}

function ProgramFeedbackContent({ programId, canManage }: { programId: number; canManage: boolean }) {
  const [data, setData] = useState<Payload>({ questions: [], events: [], stats: { responseCount: 0, averageRating: 0, registeredCount: 0, attendedCount: 0, realizedIncome: 0, realizedExpense: 0 } });
  const [form, setForm] = useState({ question: "", questionType: "rating", options: "", isRequired: true });
  const [qrEvent, setQrEvent] = useState<EventRow | null>(null); const [qrImage, setQrImage] = useState("");
  const [resultEvent, setResultEvent] = useState<EventRow | null>(null); const [resultRows, setResultRows] = useState<ResultRow[]>([]); const [resultLoading, setResultLoading] = useState(false); const [resultSearch, setResultSearch] = useState("");
  const load = useCallback(() => fetch(`/api/programs/${programId}/feedback`, { cache: "no-store" }).then(async (r) => { const p = await r.json(); if (!r.ok) throw new Error(p.error); setData(p); }), [programId]);
  useEffect(() => { void load().catch((e) => toast.error(e.message)); }, [load]);
  async function add() { const r = await fetch(`/api/programs/${programId}/feedback`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, options: form.options.split("\n") }) }); const p = await r.json(); if (!r.ok) return toast.error(p.error); setData(p); setForm({ question: "", questionType: "rating", options: "", isRequired: true }); toast.success("Pertanyaan feedback ditambahkan."); }
  async function remove(id: number) { const r = await fetch(`/api/programs/${programId}/feedback?questionId=${id}`, { method: "DELETE" }); if (!r.ok) return toast.error("Pertanyaan belum dapat dihapus."); await load(); }
  async function toggle(event: EventRow) { const r = await fetch(`/api/programs/${programId}/feedback`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ eventId: event.id, open: !event.feedbackOpen }) }); if (!r.ok) return toast.error("Status feedback belum dapat diperbarui."); await load(); }
  const feedbackUrl = (event: EventRow) => `${publicOrigin}/feedback/event/${event.id}`;
  async function copyLink(event: EventRow) { await navigator.clipboard.writeText(feedbackUrl(event)); toast.success("Link feedback umum disalin."); }
  async function showQr(event: EventRow) { setQrEvent(event); setQrImage(await QRCode.toDataURL(feedbackUrl(event), { width: 720, margin: 2, color: { dark: "#102d20", light: "#ffffff" } })); }
  async function showResults(event: EventRow) { setResultEvent(event); setResultRows([]); setResultLoading(true); try { const r = await fetch(`/api/programs/${programId}/feedback?scope=results&eventId=${event.id}`, { cache: "no-store" }); const p = await r.json(); if (!r.ok) throw new Error(p.error); setResultRows(p.rows); } catch (e) { toast.error(e instanceof Error ? e.message : "Hasil belum dapat dimuat."); } finally { setResultLoading(false); } }
  const money = new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 });
  return <section className="space-y-4 rounded-2xl border p-4"><div><h3 className="flex items-center gap-2 font-bold"><MessageSquareText className="size-5 text-primary"/>KPI Otomatis & Feedback Peserta</h3><p className="mt-1 text-xs text-muted-foreground">Angka diperbarui otomatis dari event, keuangan, dan jawaban peserta.</p></div><div className="grid grid-cols-2 gap-2 lg:grid-cols-6"><Kpi label="Pendaftar" value={String(data.stats.registeredCount)} /><Kpi label="Hadir" value={String(data.stats.attendedCount)} /><Kpi label="Penerimaan" value={money.format(data.stats.realizedIncome)} /><Kpi label="Pengeluaran" value={money.format(data.stats.realizedExpense)} /><Kpi label="Respons" value={String(data.stats.responseCount)} /><Kpi label="Rating" value={`${data.stats.averageRating || 0}/5`} /></div>
    {canManage && <div className="grid gap-3 rounded-xl bg-muted/30 p-4"><div><Label>Pertanyaan</Label><Input value={form.question} onChange={(e) => setForm({ ...form, question: e.target.value })} placeholder="Contoh: Seberapa bermanfaat materi hari ini?" /></div><div className="grid gap-3 sm:grid-cols-2"><div><Label>Tipe jawaban</Label><select value={form.questionType} onChange={(e) => setForm({ ...form, questionType: e.target.value })} className="mt-2 h-10 w-full rounded-md border bg-white px-3"><option value="rating">Rating 1–5</option><option value="text">Jawaban singkat</option><option value="paragraph">Paragraf</option><option value="select">Pilihan satu</option><option value="checklist">Checklist</option></select></div><label className="flex items-center gap-2 pt-7 text-sm"><input type="checkbox" checked={form.isRequired} onChange={(e) => setForm({ ...form, isRequired: e.target.checked })}/>Wajib diisi</label></div>{["select", "checklist"].includes(form.questionType) && <div><Label>Pilihan jawaban</Label><textarea value={form.options} onChange={(e) => setForm({ ...form, options: e.target.value })} rows={3} placeholder="Satu pilihan per baris" className="mt-2 w-full rounded-md border bg-white p-3 text-sm" /></div>}<Button type="button" onClick={add} disabled={!form.question.trim()}><Plus/>Tambah Pertanyaan</Button></div>}
    <div className="space-y-2">{data.questions.map((q, i) => <div key={q.id} className="flex items-start justify-between gap-3 rounded-xl border p-3"><div><p className="text-sm font-semibold">{i + 1}. {q.question}</p><p className="mt-1 text-xs text-muted-foreground">{questionTypeLabel(q.questionType)} · {q.isRequired ? "Wajib" : "Opsional"}</p></div>{canManage && <Button type="button" variant="ghost" size="icon-sm" className="text-rose-600" onClick={() => remove(q.id)}><Trash2/></Button>}</div>)}</div>
    {data.events.length > 0 && <div className="border-t pt-4"><h4 className="text-sm font-bold">Bagikan & Pantau Feedback per Event</h4><p className="mt-1 text-xs text-muted-foreground">Bagikan satu link atau QR kepada seluruh peserta. Link pribadi tetap tersedia pada menu Kehadiran.</p><div className="mt-3 space-y-2">{data.events.map((event) => <div key={event.id} className="rounded-xl bg-slate-50 p-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold">{event.name}</p><p className="text-xs text-muted-foreground">{event.responseCount}/{event.participantCount} peserta mengisi · {event.feedbackOpen ? "Sedang dibuka" : "Ditutup"}</p></div><div className="flex flex-wrap gap-2"><Button type="button" variant="outline" size="sm" onClick={() => copyLink(event)}><Copy/>Salin Link</Button><Button type="button" variant="outline" size="sm" onClick={() => showQr(event)}><QrCode/>QR</Button><Button type="button" variant="outline" size="sm" onClick={() => showResults(event)}><Eye/>Hasil</Button>{canManage && <Button type="button" size="sm" variant={event.feedbackOpen ? "outline" : "default"} onClick={() => toggle(event)}>{event.feedbackOpen ? "Tutup" : "Buka"} Feedback</Button>}</div></div></div>)}</div></div>}
    <Dialog open={Boolean(qrEvent)} onOpenChange={(open) => { if (!open) setQrEvent(null); }}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>QR Feedback Peserta</DialogTitle><DialogDescription>{qrEvent?.name} — tampilkan QR ini di layar atau unduh untuk dibagikan.</DialogDescription></DialogHeader>{qrImage && <div className="text-center"><Image unoptimized src={qrImage} width={720} height={720} alt={`QR feedback ${qrEvent?.name}`} className="mx-auto h-auto w-full max-w-72 rounded-2xl border p-3"/><p className="mt-3 break-all text-xs text-muted-foreground">{qrEvent && feedbackUrl(qrEvent)}</p><div className="mt-4 grid grid-cols-2 gap-2"><Button variant="outline" onClick={() => qrEvent && copyLink(qrEvent)}><Copy/>Salin Link</Button><a href={qrImage} download={`qr-feedback-${qrEvent?.id}.png`} className="inline-flex h-9 items-center justify-center gap-2 rounded-md bg-primary px-4 text-sm font-semibold text-primary-foreground"><Download className="size-4"/>Unduh QR</a></div></div>}</DialogContent></Dialog>
    <Dialog open={Boolean(resultEvent)} onOpenChange={(open) => { if (!open) setResultEvent(null); }}><DialogContent className="max-h-[90vh] max-w-[calc(100vw-2rem)] overflow-y-auto sm:max-w-6xl"><DialogHeader><DialogTitle>Hasil Feedback — {resultEvent?.name}</DialogTitle><DialogDescription>Lihat jawaban peserta, peserta yang belum mengisi, dan ekspor seluruh hasil.</DialogDescription></DialogHeader><FeedbackResults questions={data.questions} rows={resultRows} loading={resultLoading} search={resultSearch} setSearch={setResultSearch} eventName={resultEvent?.name || "event"}/></DialogContent></Dialog>
  </section>;
}

function FeedbackResults({ questions, rows, loading, search, setSearch, eventName }: { questions: Question[]; rows: ResultRow[]; loading: boolean; search: string; setSearch: (value: string) => void; eventName: string }) {
  const participants = useMemo(() => groupResults(rows), [rows]); const filtered = useMemo(() => { const q = search.trim().toLowerCase(); return participants.filter((p) => !q || `${p.participantName} ${p.phone}`.toLowerCase().includes(q)); }, [participants, search]); const submitted = participants.filter((p) => p.submittedAt).length;
  const exportExcel = () => { const headers = ["Nama Peserta", "WhatsApp", "Event", "Status", "Waktu Mengisi", ...questions.map((q) => q.question)]; const lines = [headers, ...participants.map((p) => [p.participantName, p.phone, p.eventName, p.submittedAt ? "Sudah Mengisi" : "Belum Mengisi", p.submittedAt || "", ...questions.map((q) => displayAnswer(p.answers[q.id] || ""))])]; const table = `<table>${lines.map((line) => `<tr>${line.map((cell) => `<td>${escapeHtml(String(cell))}</td>`).join("")}</tr>`).join("")}</table>`; const url = URL.createObjectURL(new Blob(["\ufeff", table], { type: "application/vnd.ms-excel;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = `hasil-feedback-${eventName.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}.xls`; a.click(); URL.revokeObjectURL(url); toast.success("Hasil feedback diekspor ke Excel."); };
  if (loading) return <div className="grid min-h-60 place-items-center text-sm text-muted-foreground">Memuat hasil feedback…</div>;
  return <div className="space-y-4"><div className="grid grid-cols-3 gap-2"><Kpi label="Peserta" value={String(participants.length)}/><Kpi label="Sudah Mengisi" value={String(submitted)}/><Kpi label="Belum Mengisi" value={String(participants.length - submitted)}/></div><div className="flex flex-col gap-2 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Cari peserta atau WhatsApp…" className="h-10 w-full rounded-xl border pl-9 pr-3 text-sm"/></label><Button onClick={exportExcel} disabled={!participants.length}><Download/>Export Excel</Button></div><QuestionSummary questions={questions} participants={participants}/><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Peserta</th><th className="p-3">Status</th>{questions.map((q) => <th key={q.id} className="min-w-48 p-3">{q.question}</th>)}</tr></thead><tbody>{filtered.map((p) => <tr key={p.participantId} className="border-t align-top"><td className="p-3"><strong>{p.participantName}</strong><p className="text-xs text-muted-foreground">{p.phone}</p></td><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs font-bold ${p.submittedAt ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-800"}`}>{p.submittedAt ? "Sudah Mengisi" : "Belum Mengisi"}</span></td>{questions.map((q) => <td key={q.id} className="whitespace-pre-wrap p-3 text-sm">{displayAnswer(p.answers[q.id] || "") || "—"}</td>)}</tr>)}</tbody></table></div></div>;
}

function QuestionSummary({ questions, participants }: { questions: Question[]; participants: ParticipantResult[] }) { return <div className="grid gap-3 lg:grid-cols-2">{questions.filter((q) => ["rating", "select", "checklist"].includes(q.questionType)).map((q) => { const values = participants.flatMap((p) => parseAnswerValues(p.answers[q.id])).filter(Boolean); const counts = new Map<string, number>(); values.forEach((v) => counts.set(v, (counts.get(v) || 0) + 1)); return <div key={q.id} className="rounded-xl border p-4"><div className="flex items-start gap-2"><BarChart3 className="mt-0.5 size-4 text-primary"/><p className="text-sm font-bold">{q.question}</p></div><div className="mt-3 space-y-2">{[...counts.entries()].sort((a,b) => b[1]-a[1]).map(([label, count]) => <div key={label}><div className="flex justify-between text-xs"><span>{label}</span><strong>{count}</strong></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-600" style={{ width: `${values.length ? count / values.length * 100 : 0}%` }}/></div></div>)}{!values.length && <p className="text-xs text-muted-foreground">Belum ada jawaban.</p>}</div></div>; })}</div>; }
function groupResults(rows: ResultRow[]) { const map = new Map<number, ParticipantResult>(); rows.forEach((row) => { if (!map.has(row.participantId)) map.set(row.participantId, { participantId: row.participantId, participantName: row.participantName, phone: row.phone, eventName: row.eventName, submittedAt: row.submittedAt, answers: {} }); const item = map.get(row.participantId)!; if (row.questionId && row.answerJson !== null) item.answers[row.questionId] = row.answerJson; }); return [...map.values()]; }
function parseAnswerValues(value: string) { if (!value) return []; try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed.map(String) : [String(parsed)]; } catch { return [value]; } }
function displayAnswer(value: string) { return parseAnswerValues(value).join(", "); }
function escapeHtml(value: string) { return value.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c] || c)); }
function questionTypeLabel(type: string) { return ({ rating: "Rating 1–5", text: "Jawaban singkat", paragraph: "Paragraf", select: "Pilihan satu", checklist: "Checklist" } as Record<string,string>)[type] || type; }
function Kpi({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-emerald-50 p-3"><p className="text-xs text-emerald-800">{label}</p><p className="mt-1 font-bold text-emerald-950">{value}</p></div>; }
