"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, ExternalLink, ImageUp, LoaderCircle, Megaphone, Share2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { publicHost, publicOrigin } from "@/lib/public-origin";

type Publication = { programCode: string; programTitle: string; isPublished: number; publicTitle: string; tagline: string; description: string; benefits: string; audience: string; contactName: string; contactPhone: string; registrationEventId: number | null; isFeatured: number; flyerKey: string | null };
type Event = { id: number; name: string; eventDate: string; registrationOpen: number; isPaid: number };

export default function ProgramPublication({ programId, canManage }: { programId: number; canManage: boolean }) {
  const [data, setData] = useState<Publication | null>(null); const [events, setEvents] = useState<Event[]>([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [flyer, setFlyer] = useState<File | null>(null);
  useEffect(() => { let active = true; fetch(`/api/programs/${programId}/publication`).then(async (r) => { const p = await r.json(); if (!r.ok) throw new Error(p.error); if (active) { setData(p.publication); setEvents(p.events); } }).catch((e) => toast.error(e.message)).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [programId]);
  if (loading) return <section className="rounded-2xl border bg-white p-5"><p className="flex items-center gap-2 text-sm text-muted-foreground"><LoaderCircle className="size-4 animate-spin" />Memuat pengaturan publikasi…</p></section>;
  if (!data) return null;
  const publicUrl = `${publicOrigin()}/program/${data.programCode.toLowerCase()}`;
  async function save() { if (!data) return; setSaving(true); try { const form = new FormData(); Object.entries({ isPublished: Boolean(data.isPublished), publicTitle: data.publicTitle || data.programTitle, tagline: data.tagline, description: data.description, benefits: data.benefits, audience: data.audience, contactName: data.contactName, contactPhone: data.contactPhone, registrationEventId: data.registrationEventId || "", isFeatured: Boolean(data.isFeatured) }).forEach(([k,v]) => form.set(k, String(v))); if (flyer) form.set("flyer", flyer); const r = await fetch(`/api/programs/${programId}/publication`, { method: "PATCH", body: form }); const p = await r.json(); if (!r.ok) throw new Error(p.error); setData(p.publication); setFlyer(null); toast.success(data.isPublished ? "Program berhasil dipublikasikan untuk member." : "Pengaturan publikasi berhasil disimpan."); } catch(e) { toast.error(e instanceof Error ? e.message : "Belum dapat disimpan."); } finally { setSaving(false); } }
  function change<K extends keyof Publication>(key: K, value: Publication[K]) { setData({ ...data, [key]: value }); }
  return <section className="rounded-2xl border bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Megaphone className="size-5" /></span><div><h3 className="font-bold">Publikasi untuk Member</h3><p className="mt-1 text-sm text-muted-foreground">Atur tampilan program pada etalase publik tanpa membuka data internal.</p></div></div>{data.isPublished ? <span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700"><CheckCircle2 className="size-4" />Sudah tayang</span> : <span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold text-slate-600">Belum tayang</span>}</div>
    <div className="grid gap-5 p-5 lg:grid-cols-[1fr_.72fr]"><div className="grid gap-4"><label className="flex items-center justify-between rounded-xl border p-4"><span><strong className="block text-sm">Tampilkan kepada member</strong><span className="text-xs text-muted-foreground">Program muncul di {publicHost()}/program</span></span><input type="checkbox" checked={Boolean(data.isPublished)} disabled={!canManage} onChange={(e) => change("isPublished", e.target.checked ? 1 : 0)} className="size-5 accent-emerald-700" /></label><div className="grid gap-2"><Label>Judul publik</Label><Input value={data.publicTitle || data.programTitle} disabled={!canManage} onChange={(e) => change("publicTitle", e.target.value)} /></div><div className="grid gap-2"><Label>Kalimat pembuka</Label><Input value={data.tagline} disabled={!canManage} onChange={(e) => change("tagline", e.target.value)} placeholder="Contoh: Bangun fondasi bisnis yang lebih rapi bersama TDA" /></div><div className="grid gap-2"><Label>Tentang program</Label><Textarea rows={4} value={data.description} disabled={!canManage} onChange={(e) => change("description", e.target.value)} placeholder="Jelaskan program dengan bahasa yang menarik untuk member…" /></div><div className="grid gap-2"><Label>Manfaat <span className="font-normal text-muted-foreground">(satu manfaat per baris)</span></Label><Textarea rows={4} value={data.benefits} disabled={!canManage} onChange={(e) => change("benefits", e.target.value)} /></div><div className="grid gap-2"><Label>Program ini cocok untuk</Label><Textarea rows={3} value={data.audience} disabled={!canManage} onChange={(e) => change("audience", e.target.value)} /></div></div>
      <div className="space-y-4"><div className="rounded-xl border p-4"><div className="flex items-center gap-2"><ImageUp className="size-5 text-primary" /><Label>Flyer Program</Label></div>{data.flyerKey && <img src={`/api/public-programs/${data.programCode}/flyer`} alt="Flyer program" className="mx-auto mt-3 aspect-[4/5] max-h-72 rounded-xl border object-cover" />}<Input type="file" accept=".jpg,.jpeg,.png,.webp" disabled={!canManage} onChange={(e) => setFlyer(e.target.files?.[0] || null)} className="mt-3" /><p className="mt-2 text-xs text-muted-foreground">Disarankan rasio 4:5, maksimal 5 MB.</p></div><div className="grid gap-2"><Label>Event pendaftaran</Label><select value={data.registrationEventId || ""} disabled={!canManage} onChange={(e) => change("registrationEventId", Number(e.target.value) || null)} className="h-10 rounded-md border bg-white px-3 text-sm"><option value="">Belum dihubungkan</option>{events.map((event) => <option key={event.id} value={event.id}>{event.name} · {event.registrationOpen ? "Dibuka" : "Ditutup"}</option>)}</select></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1 xl:grid-cols-2"><div className="grid gap-2"><Label>Narahubung</Label><Input value={data.contactName} disabled={!canManage} onChange={(e) => change("contactName", e.target.value)} /></div><div className="grid gap-2"><Label>WhatsApp</Label><Input value={data.contactPhone} disabled={!canManage} onChange={(e) => change("contactPhone", e.target.value)} placeholder="628…" /></div></div><label className="flex items-center gap-3 rounded-xl border p-3 text-sm font-semibold"><input type="checkbox" checked={Boolean(data.isFeatured)} disabled={!canManage} onChange={(e) => change("isFeatured", e.target.checked ? 1 : 0)} className="size-5 accent-emerald-700" />Jadikan program unggulan</label>{data.isPublished && <div className="grid grid-cols-2 gap-2"><Button asChild variant="outline"><a href={publicUrl} target="_blank"><ExternalLink />Pratinjau</a></Button><Button variant="outline" onClick={() => navigator.clipboard.writeText(publicUrl).then(() => toast.success("Link program disalin."))}><Share2 />Salin Link</Button></div>}{canManage && <Button onClick={() => void save()} disabled={saving} className="w-full">{saving && <LoaderCircle className="animate-spin" />}{data.isPublished ? "Simpan & Publikasikan" : "Simpan Pengaturan"}</Button>}</div></div>
  </section>;
}
