"use client";

import { useState } from "react";
import {
  ArrowLeft, ArrowRight, BarChart3, CheckCircle2, ClipboardCheck, Eye, FileCheck2,
  HelpCircle, ListFilter, MessageSquareText, Pencil, Plus, Search, Trash2, UsersRound, WalletCards, X,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Progress } from "@/components/ui/progress";

const steps = [
  { title: "Mengenal Daftar Program", description: "Halaman ini menjadi pusat pengelolaan seluruh Program Kerja. Setiap baris menampilkan kode, nama program, divisi, PIC, status, progres pekerjaan, dan capaian KPI.", visual: "list" },
  { title: "Cari dan Saring Program", description: "Gunakan pencarian untuk menemukan program berdasarkan nama, kode, PIC, target, atau divisi. Filter Divisi dan Status membantu mempersempit daftar yang tampil.", visual: "filter" },
  { title: "Buat Program Kerja", description: "Pengurus yang memiliki izin dapat menekan Tambah Program, lalu mengisi nama, divisi, PIC, waktu pelaksanaan, estimasi anggaran, target keberhasilan, dan ringkasan.", visual: "create" },
  { title: "Buka dan Kelola Program", description: "Tekan Detail untuk membuka seluruh kontrol program. Tombol Edit dan Hapus hanya tampil kepada pengurus yang memiliki kewenangan sesuai divisi dan status program.", visual: "actions" },
  { title: "Ajukan Persetujuan", description: "Program dimulai sebagai Draft. Setelah datanya siap, ajukan kepada Ketua/KSB. Hasilnya dapat berupa Disetujui, Perlu Revisi, atau Ditolak beserta catatan.", visual: "approval" },
  { title: "Susun Breakdown Pekerjaan", description: "Tambahkan setiap pekerjaan, PIC, due date, status, kebutuhan anggaran, dan divisi pelaksana. Divisi yang dilibatkan akan menerima notifikasi.", visual: "tasks" },
  { title: "Kontrol Anggaran dan Realisasi", description: "Pekerjaan yang menggunakan anggaran dapat dihubungkan dengan penerimaan atau pengeluaran pada Keuangan & LPJ. Sistem membantu melihat realisasi dan potensi over budget.", visual: "finance" },
  { title: "Ukur KPI Program", description: "Tambahkan indikator seperti jumlah peserta, penerimaan, pengeluaran, atau target lainnya. Perbarui realisasinya agar capaian program dapat dipantau.", visual: "kpi" },
  { title: "Bagikan dan Lihat Feedback", description: "Buat pertanyaan feedback sesuai kebutuhan program, lalu bagikan satu link atau QR kepada peserta. Hasilnya dapat dilihat sebagai ringkasan, jawaban peserta, dan diekspor ke Excel.", visual: "feedback" },
] as const;

export default function ProgramGuide({ canCreate }: { canCreate: boolean }) {
  const [open, setOpen] = useState(false);
  const [step, setStep] = useState(0);
  const current = steps[step];
  function close() { setOpen(false); window.localStorage.setItem("tdapku-program-guide-seen", "1"); }
  return <>
    <Button type="button" variant="outline" onClick={() => { setStep(0); setOpen(true); }} className="shrink-0"><HelpCircle className="size-4" />Petunjuk</Button>
    <Dialog open={open} onOpenChange={(next) => { if (!next) close(); else setOpen(true); }}>
      <DialogContent className="h-[100dvh] max-h-none w-screen max-w-none overflow-y-auto rounded-none border-0 p-0 sm:h-auto sm:max-h-[92vh] sm:w-[calc(100vw-2rem)] sm:max-w-5xl sm:rounded-3xl sm:border">
        <DialogHeader className="sticky top-0 z-10 border-b bg-white px-5 py-4 text-left sm:px-7">
          <div className="flex items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-700">Petunjuk Program Kerja · Langkah {step + 1} dari {steps.length}</p><DialogTitle className="mt-1 text-xl sm:text-2xl">{current.title}</DialogTitle></div><button onClick={close} className="grid size-10 shrink-0 place-items-center rounded-full bg-slate-100" aria-label="Tutup petunjuk"><X className="size-5" /></button></div>
          <DialogDescription className="sr-only">Panduan penggunaan menu Program Kerja tdapku.</DialogDescription><Progress value={(step + 1) / steps.length * 100} className="mt-3" />
        </DialogHeader>
        <div className="grid gap-6 p-5 sm:p-7 lg:grid-cols-[1.35fr_.65fr] lg:items-center"><GuideVisual kind={current.visual} /><div><div className="rounded-2xl bg-emerald-50 p-5"><div className="grid size-10 place-items-center rounded-xl bg-emerald-700 font-bold text-white">{step + 1}</div><p className="mt-4 text-base leading-7 text-emerald-950">{current.description}</p></div><div className="mt-4 rounded-2xl border p-4"><p className="text-sm font-bold">Yang perlu dilakukan</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{instructionFor(current.visual, canCreate)}</p></div></div></div>
        <div className="sticky bottom-0 flex items-center justify-between gap-3 border-t bg-white px-5 py-4 sm:px-7"><Button variant="outline" disabled={step === 0} onClick={() => setStep((value) => Math.max(0, value - 1))}><ArrowLeft />Sebelumnya</Button><div className="hidden gap-1.5 sm:flex">{steps.map((_, index) => <button key={index} onClick={() => setStep(index)} aria-label={`Langkah ${index + 1}`} className={`size-2.5 rounded-full ${index === step ? "bg-emerald-700" : "bg-slate-200"}`} />)}</div>{step < steps.length - 1 ? <Button onClick={() => setStep((value) => Math.min(steps.length - 1, value + 1))}>Selanjutnya<ArrowRight /></Button> : <Button onClick={close}><CheckCircle2 />Selesai</Button>}</div>
      </DialogContent>
    </Dialog>
  </>;
}

function GuideVisual({ kind }: { kind: typeof steps[number]["visual"] }) {
  return <div className="overflow-hidden rounded-2xl border bg-[#f5f8f5] p-3 shadow-inner sm:p-5"><div className="mb-3 flex items-center justify-between rounded-xl bg-[#102d20] p-3 text-white"><strong className="text-sm">Daftar Program Kerja</strong><span className="rounded-lg bg-emerald-500 px-2 py-1 text-xs font-bold">PRG-2026</span></div>
    {kind === "list" && <MockList />}
    {kind === "filter" && <><div className="grid gap-2 sm:grid-cols-3"><MockControl icon={Search} label="Cari program atau PIC…" /><MockControl icon={UsersRound} label="Semua divisi" /><MockControl icon={ListFilter} label="Semua status" /></div><div className="mt-3"><MockList /></div></>}
    {kind === "create" && <div className="rounded-xl bg-white p-4"><div className="flex items-center justify-between"><strong>Tambah Program Kerja</strong><span className="grid size-9 place-items-center rounded-lg bg-emerald-700 text-white"><Plus className="size-5" /></span></div><div className="mt-4 grid grid-cols-2 gap-2">{["Nama program", "Divisi", "PIC", "Estimasi anggaran", "Tanggal mulai", "Target selesai", "Target keberhasilan", "Ringkasan"].map((label, i) => <div key={label} className={`rounded-lg border p-2.5 ${i > 5 ? "col-span-2" : ""}`}><p className="text-[11px] font-bold text-slate-500">{label}</p><div className="mt-2 h-2 rounded bg-slate-100" /></div>)}</div></div>}
    {kind === "actions" && <div className="rounded-xl border-2 border-emerald-600 bg-white p-4"><p className="font-mono text-xs font-bold text-emerald-700">PRG-2026-0012</p><h3 className="mt-1 font-bold">Kelas Reguler TDA</h3><div className="mt-4 grid grid-cols-3 gap-2"><Action icon={Eye} label="Detail" /><Action icon={Pencil} label="Edit" /><Action icon={Trash2} label="Hapus" danger /></div></div>}
    {kind === "approval" && <div className="space-y-2">{[["Draft", "Siapkan data"], ["Menunggu Approval", "Diperiksa Ketua/KSB"], ["Disetujui", "Siap dilaksanakan"]].map(([label, note], i) => <div key={label} className={`flex items-center gap-3 rounded-xl border-2 bg-white p-3 ${i === 1 ? "border-amber-500" : i === 2 ? "border-emerald-500" : "border-slate-200"}`}><span className="grid size-8 place-items-center rounded-full bg-slate-100 text-xs font-bold">{i + 1}</span><div><p className="text-sm font-bold">{label}</p><p className="text-xs text-muted-foreground">{note}</p></div></div>)}</div>}
    {kind === "tasks" && <div className="space-y-2">{["Susun materi kelas", "Konfirmasi pembicara", "Siapkan meja registrasi"].map((label, i) => <div key={label} className="rounded-xl border bg-white p-3"><div className="flex justify-between gap-3"><strong className="text-sm">{label}</strong><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${i === 2 ? "bg-amber-100 text-amber-800" : "bg-emerald-100 text-emerald-800"}`}>{i === 2 ? "Dikerjakan" : "Selesai"}</span></div><div className="mt-2 flex gap-2 text-[11px] text-slate-500"><span>PIC: Tim Event</span><span>•</span><span>Divisi Edukasi</span></div></div>)}</div>}
    {kind === "finance" && <div className="grid grid-cols-2 gap-3"><Metric icon={WalletCards} label="Anggaran" value="Rp10.000.000" /><Metric icon={FileCheck2} label="Realisasi" value="Rp8.250.000" /><div className="col-span-2 rounded-xl border-2 border-emerald-500 bg-white p-4"><div className="flex justify-between text-sm"><span>Sisa anggaran</span><strong className="text-emerald-700">Rp1.750.000</strong></div><Progress value={82.5} className="mt-3" /></div></div>}
    {kind === "kpi" && <div className="rounded-xl bg-white p-4"><div className="flex items-center gap-2"><BarChart3 className="size-5 text-emerald-700" /><strong>Capaian KPI</strong></div><div className="mt-4 space-y-4"><Kpi label="Peserta hadir" value="86 / 100" progress={86} /><Kpi label="Penerimaan" value="Rp12 jt / Rp15 jt" progress={80} /><Kpi label="Kepuasan peserta" value="92%" progress={92} /></div></div>}
    {kind === "feedback" && <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-white p-4"><MessageSquareText className="size-6 text-emerald-700" /><p className="mt-3 text-sm font-bold">Link & QR Feedback</p><div className="mt-3 grid aspect-square max-w-24 grid-cols-4 gap-1 rounded-lg bg-slate-900 p-2">{Array.from({ length: 16 }, (_, i) => <span key={i} className={i % 3 === 0 || i % 5 === 0 ? "bg-white" : "bg-slate-900"} />)}</div></div><div className="rounded-xl bg-white p-4"><ClipboardCheck className="size-6 text-emerald-700" /><p className="mt-3 text-sm font-bold">Hasil Peserta</p><p className="mt-2 text-3xl font-bold">24</p><p className="text-xs text-slate-500">sudah mengisi</p><Button size="sm" className="mt-4 w-full">Export Excel</Button></div></div>}
  </div>;
}

function MockList() { return <div className="space-y-2">{[["PRG-2026-0012", "Kelas Reguler TDA", "65%"], ["PRG-2026-0011", "TDA Member Bazaar", "100%"]].map(([code, title, progress], i) => <div key={code} className="rounded-xl border bg-white p-3"><div className="flex justify-between gap-3"><div><p className="font-mono text-[10px] font-bold text-emerald-700">{code}</p><p className="mt-1 text-sm font-bold">{title}</p></div><span className={`h-fit rounded-full px-2 py-1 text-[10px] font-bold ${i ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-800"}`}>{i ? "Disetujui" : "Menunggu Approval"}</span></div><div className="mt-3 flex items-center gap-2"><Progress value={Number(progress.replace("%", ""))} /><strong className="text-xs">{progress}</strong></div></div>)}</div>; }
function MockControl({ icon: Icon, label }: { icon: typeof Search; label: string }) { return <div className="flex items-center gap-2 rounded-lg border bg-white p-2.5 text-xs text-slate-500"><Icon className="size-4" /><span className="truncate">{label}</span></div>; }
function Action({ icon: Icon, label, danger = false }: { icon: typeof Eye; label: string; danger?: boolean }) { return <div className={`grid place-items-center rounded-lg border p-3 text-xs font-bold ${danger ? "text-rose-600" : "text-emerald-800"}`}><Icon className="mb-1 size-5" />{label}</div>; }
function Metric({ icon: Icon, label, value }: { icon: typeof WalletCards; label: string; value: string }) { return <div className="rounded-xl border bg-white p-4"><Icon className="size-5 text-emerald-700" /><p className="mt-3 text-xs text-slate-500">{label}</p><p className="mt-1 text-sm font-bold">{value}</p></div>; }
function Kpi({ label, value, progress }: { label: string; value: string; progress: number }) { return <div><div className="flex justify-between gap-3 text-xs"><span>{label}</span><strong>{value}</strong></div><Progress value={progress} className="mt-2" /></div>; }
function instructionFor(kind: typeof steps[number]["visual"], canCreate: boolean) { return ({ list: "Periksa status, progres pekerjaan, dan capaian KPI sebelum membuka program yang perlu ditindaklanjuti.", filter: "Ketik kata kunci atau pilih Divisi dan Status. Tekan Reset filter untuk kembali melihat semua program.", create: canCreate ? "Tekan Tambah Program dan lengkapi data utamanya. Kode program dibuat otomatis oleh sistem." : "Akun Anda berada dalam mode pantau. Pembuatan program hanya tersedia untuk pengurus dengan izin kelola.", actions: "Tekan Detail untuk membuka kontrol lengkap. Gunakan Edit atau Hapus hanya bila diperlukan dan tombolnya tersedia.", approval: "Lengkapi program saat masih Draft, kemudian ajukan approval. Periksa catatan jika program diminta direvisi.", tasks: "Pecah program menjadi pekerjaan yang jelas, tetapkan PIC dan tenggat, lalu pilih seluruh divisi yang terlibat.", finance: "Aktifkan anggaran pada pekerjaan yang membutuhkan biaya, kemudian catat realisasinya melalui Keuangan & LPJ.", kpi: "Buat KPI yang dapat diukur, isi target dan realisasi, lalu pantau persentase capaiannya.", feedback: "Susun pertanyaan, bagikan link atau QR bersama kepada peserta, lalu lihat ringkasan dan ekspor hasilnya." } as Record<string, string>)[kind]; }
